### ISSUE TITLE
Application error when trying to access a post

### ISSUE THREAD

**Issue by fveauvy** [vercel/platforms#14] opened 2022-01-21 12:50 UTC
I created the following test site : [Test3](https://test3.vercel.pub/)

And then published a post with this markdown content : [pastebin](https://pastebin.com/iESRiXkY)

When I'm trying to access the post [here](https://test3.vercel.pub/hello-world), I encounter a Application Error.

> Application error: a client-side exception has occurred (see the browser console for more information).

Here's my console output :

<img width="522" alt="Screenshot 2022-01-21 at 13 46 32" src="https://user-images.githubusercontent.com/38651917/150529824-40c44a75-893e-477e-a87e-023a1ea2f717.png">

**Comment by steven-tey** [comment] 2022-01-22 20:21
Thanks for posting this @fveauvy! I actually ran into this as well yesterday – I think it's caused by an unescaped `<img>` tag. For some reason `remark` is converting the inline markdown images into `<img src="" alt"">` without escaping it properly, which is causing this error. Another reason is probably due to the code snippet (it breaks the editor at the moment). Can you try removing both the images and inline code snippets and see if the error persists?

**Comment by fveauvy** [comment] 2022-01-23 22:59
Hey @steven-tey,

Indeed, if I remove both the code snippet and the inline image `![](link)` the page is loading accordingly.

**Comment by steven-tey** [comment] 2022-01-29 02:23
This should be fixed by #37 and #32! I created a little [kitchen sink example here](https://steven.vercel.pub/kitchen-sink) that displays all the capabilities of the text editor :)

**Closed by steven-tey** 2022-01-29 02:23 UTC
