### ISSUE TITLE
Current Build & Guide Fail

### ISSUE THREAD

**Issue by perkail** [vercel/platforms#225] opened 2023-06-28 01:23 UTC
The current build is failing, and the guide doesn't work, as I can't get anything to load locally or on Vercel. Does anyone know when this template might have a stable build?

**Comment by FredvanRijswijk** [comment] 2023-07-04 10:46
```"next": "13.4.8"``` 

and 

```// rewrite root application to `/home` folder
  if (hostname === "localhost:3000" || hostname === process.env.NEXT_PUBLIC_ROOT_DOMAIN) {```

**Comment by perkail** [comment] 2023-07-05 16:58
Thanks. This has been killing me.

**Comment by steven-tey** [comment] 2023-07-05 22:05
Closing as a duplicate of #232

**Closed by steven-tey** 2023-07-05 22:05 UTC
