### ISSUE TITLE
Router.push Shallow writing wrong URL using Middleware NextResponse.rewrite(url)

### ISSUE THREAD

**Issue by minardimedia** [vercel/platforms#113] opened 2022-06-02 00:31 UTC
I am using the platform code to write a multitenat application.

When I perform a shallow router push in one of the subdomain URLs the url writes wrong extra information

Working in localhost with subdomains 

Original URL `http://casablanca.nomadtest.com:3001/room/20991d5b-c321-4b75-9c01-4fc85e7a4c3d`

Run the Router.push

```
          router.push(
            {
              query: {
                site: router.query.site,
                id: router.query.id,
                start_date: "12-12-2022",
              },
            },
            undefined,
            {
              shallow: true,
            }
          );
```

This provoke a whole page hard reload 

Resulting URL `http://casablanca.nomadtest.com:3001/_sites/casablanca/room/20991d5b-c321-4b75-9c01-4fc85e7a4c3d?start_date=12-12-2022`

It add extra "_sites/casablanca/"

Expected URL: `http://casablanca.nomadtest.com:3001/room/20991d5b-c321-4b75-9c01-4fc85e7a4c3d?start_date=12-12-2022`

Avoid page reload

Here is the middleware handling the rewrite

```
export default function middleware(req: NextRequest) {
  const url = req.nextUrl.clone();
  const { pathname } = req.nextUrl;
  const hostname = req.headers.get("host");
  const currentHost = hostname!.replace(`.nomadtest.com:3001`, "");

  if (pathname.startsWith(`/_sites`)) {
    return new Response(null, { status: 404 });
  }

  if (!pathname.includes(".") && !pathname.startsWith("/api")) {
    if (currentHost === "host") {
      url.pathname = `/host${pathname}`;
      return NextResponse.rewrite(url);
    } else if (hostname === "nomadtest.com:3001") {
      return NextResponse.rewrite(url);
    } else {
      url.pathname = `/_sites/${currentHost}${pathname}`;
      return NextResponse.rewrite(url);
    }
  }
  return NextResponse.rewrite(url);
}
```

**Comment by steven-tey** [comment] 2022-08-12 15:54
Hey @minardimedia! So sorry for the late response – this should've been fixed with our [new middleware here](https://github.com/vercel/platforms/blob/main/middleware.ts). Please try it out and let me know if it works!

I'll close this issue for now but feel free to reopen it if there are any other issues!

**Closed by steven-tey** 2022-08-12 15:54 UTC

**Comment by sinclairnick** [comment] 2022-09-14 23:53
Hey @steven-tey, just so you know I'm currently running into this issue (`next@12.3.0`).

Using both shallow and non-shallow routing, I'm experiencing the same behaviour as above.

Any ideas on how to resolve this?

**Comment by heymartinadams** [comment] 2023-02-09 23:47
@steven-tey, as far as I can tell, the issue doesn’t seem to be with the middleware, but with the `router` handler.

1. Middleware `rewrites` a path to a hidden folder (e.g. `/_sites/[site]`)
2. Router pushes a shallow update to the queries, and it results in `/_sites/[site]?somequery=true` appearing in the URL.

How does one do a shallow router push considering the hidden folder?

Note: if I do something like `router.push({ pathname: router.pathname.replace('/_sites/[site]', '')` it then ends up constantly reloading the page.

**Comment by heymartinadams** [comment] 2023-02-10 00:01
@minardimedia and @sinclairnick were you able to resolve this? It’s driving me stark mad... spent an entire day on this so far, with no solution in sight.

**Comment by minardimedia** [comment] 2023-02-10 00:38
@heymartinadams  I think at the end I didn't use the router push I think the reason I wanted to implement this was so I can persist the url state in the query. So I use a library called Jotai they have a couple cool ways to store the data and read data from the url if I am not wrong I use the atomWithHash() hook so at the end I just use the <Link> component  and form the url string like this 

`
 href = `/room/${room.id}/book#${guestsStringQuery(
      guests
    )}&check_in=${checkIn.format("YYYY-MM-DD")}&check_out=${checkOut.format(
      "YYYY-MM-DD"
    )}`;
` 
So there is a store that keeps in sync check_in  check_out data

Here is the library [Jotai Location](https://jotai.org/docs/integrations/location)  hope this can help in your use case

**Comment by heymartinadams** [comment] 2023-02-11 17:32
Thank you, @minardimedia! I'll use that library if I can't get `router.push` to work.

From what I can tell, `router.push(..., undefined, { shallow: true })` fires middleware to `rewrite` to the subdomain, which in turn causes the page to load anew, as if non-shallow routing had occurred.

**Comment by heymartinadams** [comment] 2023-02-11 17:37
@steven-tey do you think this issue is merely due to an incorrect configuration of middleware, or a flaw in `router` when combined with middleware and subdomains?

**Comment by heymartinadams** [comment] 2023-02-14 06:17
@steven-tey I posted this issue, with reproduction, on the main `next` site, because the issue does indeed seem to lie with `next/router`. https://github.com/vercel/next.js/issues/45886

**Comment by heymartinadams** [comment] 2023-02-14 16:55
And solved! Posting here in case someone else is running into the same issue. https://github.com/vercel/next.js/issues/45886#issuecomment-1430058617

**Comment by kant01ne** [comment] 2023-02-21 02:01
I have a similar setup to this repo but I'm using the app directory. It doesn't seem like the router imported from `next/navigation` supports shallow routing. Any hint to solve that? 
cc @steven-tey I see that you've started to have a look at moving to the app directory in https://github.com/vercel/platforms/pull/161
